apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: develop-binding
spec:
  params:
  - name: revision
    value: $(body.head_commit.id)
  - name: repositoryUrl
    value: $(body.repository.git_ssh_url)
  - name: branch
    value: $(body.ref)