apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: develop-trigger-binding
spec:
  params:
    - name: url
      value: $(body.repository.url)
    - name: revision
      value: $(body.ref)
