
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: develop-template
spec:
  params:
  - name: revision
    description: The git revision
    default: develop
  - name: repositoryUrl
    description: The git repository url
    default: ""
  - name: branch
    description: The git branch
    default: develop
  tasks:
    - name: develop-pipeline-run
      taskRef:
        name: develop-pipeline
      params:
        - name: url
          value: $(tt.params.repositoryUrl)
        - name: revision
          value: $(tt.params.branch)
