apiVersion: v1
kind: Service
metadata:
  name: lpg-mis-api-service
  namespace: test-environment
spec:
  selector:
    app: lpg-mis-api
  ports:
    - protocol: TCP
      port: 9998
      targetPort: 9998
  type: LoadBalancer
