apiVersion: apps/v1
kind: Deployment
metadata:
  name: lpg-api-deployment
  namespace: test-environment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lpg-api
  template:
    metadata:
      labels:
        app: lpg-api
    spec:
      containers:
      - name: lpg-api
        image: lpg_api:latest  # This remains constant; the tag will be dynamically changed
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /data  # Mount path in the container
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: lpg-mis-api-pvc
