apiVersion: apps/v1
kind: Deployment
metadata:
  name: lpg-mis-api-deployment
  namespace: test-environment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lpg-mis-api
  template:
    metadata:
      labels:
        app: lpg-mis-api
    spec:
      containers:
      - name: lpg-mis-api
        image: tiqurabeba/lpg-mis-api:latest
        ports:
        - containerPort: 9998
        volumeMounts:
        - name: data
          mountPath: /data  # Mount path in the container
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: lpg-mis-api-pvc
