apiVersion: apps/v1
kind: Deployment
metadata:
  name: lpg-mis-api-deployment-production
  namespace: production-environment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lpg-mis-api
      env: production
  template:
    metadata:
      labels:
        app: lpg-mis-api
        env: production
    spec:
      containers:
      - name: lpg-mis-api
        image: tiqurabeba/lpg-mis-api:latest
        ports:
        - containerPort: 9998
        volumeMounts:
        - name: data
          mountPath: /data  # Mount path in the container
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: lpg-mis-api-pvc-production
