apiVersion: apps/v1
kind: Deployment
metadata:
  name: lpg-mis-api-deployment-develop
  namespace: test-environment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lpg-mis-api
      env: test
  template:
    metadata:
      labels:
        app: lpg-mis-api
        env: test
    spec:
      containers:
      - name: lpg-mis-api
       # image: tiqurabeba/lpg-mis-api:0.1
        image: tiqurabeba/lpg-mis-api:0.2
        ports:
        - containerPort: 9998
        volumeMounts:
        - name: data
          mountPath: /data  # Mount path in the container
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: lpg-mis-api-pvc-develop
