apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lpg-mis-api-pvc-develop
  namespace: test-environment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
