apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: develop-deploy-to-gke
spec:
  steps:
    - name: develop-deploy-to-gke
      image: google/cloud-sdk
      command:
        - /bin/bash
      args:
        - -c
        - |
          gcloud container clusters get-credentials lpg-mis --zone africa-south1 --project single-cistern-420705
          kubectl apply -f develop-deployment.yaml
