apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: develop-pipeline
  namespace: test-environment
spec:
  params:
    - name: branch
      description: GitHub branch
      default: develop
  tasks:
    - name: develop-build-push-to-docker-hub
      taskRef:
        name: develop-build-push-to-docker-hub
      params:
        - name: git-url
          value: https://github.com/frankkamando/GasManagementSystemAPI.git
        - name: git-revision
          value: develop
        - name: docker-image
          value: lpg-mis-api
        - name: docker-tag
          value: v0.3
        - name: docker-username
          value: tiqurabeba
        - name: github-username
          value: Abduswamad
    # - name: develop-deploy-to-gke
    #   taskRef:
    #     name: develop-deploy-to-gke
    
