apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: develop-clone-code
  namespace: test-environment
spec:
  description: Clone a Git repository
  workspaces:
  - name: output  
  params:
  - name: url
    type: string
    description: The URL of the Git repository to clone
  steps:
  - name: git-clone
    image: alpine/git
    script: |
      #!/bin/sh
      git clone $(params.url) $(workspaces.output.path)
 
