apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: develop-deploy-to-gke
spec:
  params:
    - name: branch
      description: GitHub branch
      default: develop   # Set the default branch to "develop"
  steps:
    - name: fetch-source
      image: alpine/git
      env:
        - name: GITHUB_USERNAME
          valueFrom:
            secretKeyRef:
              name: abdul-github-credentials
              key: username
        - name: GITHUB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: abdul-github-credentials
              key: password
      args:
        - sh
        - -c
        - |
          git clone --single-branch --branch $(params.branch) https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/frankkamando/GasManagementSystemAPI.git /workspace/source
    - name: gke-deploy
      image: google/cloud-sdk:latest
      command:
        - sh
      args:
        - -c
        - |
          gcloud container clusters get-credentials lpg-mis --region africa-south1
          kubectl apply -f develop-deployment.yaml
