apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-cluster-role
rules:
- apiGroups: ["", "apps", "extensions"]
  resources: ["deployments" ,"nodes", "pods"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
