apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  description: Clone a Git repository
  workspaces:
  - name: output  # Add this workspace definition
  params:
  - name: url
    type: string
    description: The URL of the Git repository to clone
  steps:
  - name: git-clone
    image: alpine/git
    script: |
      #!/bin/sh
      git clone $(params.url) $(workspaces.output.path)
