name: deploy-action
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_TAG: tiqurabeba/lpg-mis-api:v0.1  # Define the Docker image tag as an environment variable
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: tiqurabeba
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE_TAG }}  # Reference the environment variable here

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: single-cistern-420705
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker
          
      - name: Authenticate with Google Cloud
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > /tmp/gcp_sa_key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp_sa_key.json

      - name: Install kubectl
        run: |
          gcloud components install kubectl

      - name: Deploy to GKE
        run: |
          # Replace the following commands with your deployment commands
          gcloud container clusters get-credentials lpg-mis --zone africa-south1 --project single-cistern-420705
          kubectl apply -f - <<EOF
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: lpg-mis-api-deployment-develop
            namespace: test-environment
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: lpg-mis-api
                env: test
            template:
              metadata:
                labels:
                  app: lpg-mis-api
                  env: test
              spec:
                containers:
                - name: lpg-mis-api
                  image: $DOCKER_IMAGE_TAG  # Reference the environment variable here
                  ports:
                  - containerPort: 9998
                  volumeMounts:
                  - name: data
                    mountPath: /data  # Mount path in the container
                volumes:
                - name: data
                  persistentVolumeClaim:
                    claimName: lpg-mis-api-pvc-develop
          EOF
