name: Deploy to GKE

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --tag lpi-mis-api:0.1 \
            .
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'single-cistern-420705.svc.id.goog'
          service_account: '490741108981-compute@developer.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      # - name: Authenticate with Google Cloud
      #   run: |
      #     echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > gcp-auth-key.json
      #     gcloud auth activate-service-account --key-file=gcp-auth-key.json
      #   env:
      #     GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GCP_AUTH_TOKEN }}


      # - name: Set the project ID
      #   run: gcloud config set project single-cistern-420705
      
      # - name: Authenticate with the GKE cluster
      #   run: gcloud container clusters get-credentials lpg-mis --region africa-south1 --project single-cistern-420705
      
      # - name: Apply Kubernetes deployment
      #   run: |
      #     kubectl apply -f - <<EOF
      #     apiVersion: apps/v1
      #     kind: Deployment
      #     metadata:
      #       name: lpi-mis-api
      #       namespace: test
      #       labels:
      #         app: lpi-mis-api
      #     spec:
      #       replicas: 3
      #       selector:
      #         matchLabels:
      #           app: lpi-mis-api
      #       template:
      #         metadata:
      #           labels:
      #             app: lpi-mis-api
      #         spec:
      #           containers:
      #           - name: lpi-mis-api
      #             image: lpi-mis-api:0.1
      #             ports:
      #             - containerPort: 9998
      #     EOF
