name: Deploy to GKE

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --tag gcr.io/your-project/lpi-mis-api:0.1 \
            .
      
      - name: Configure Docker CLI
        uses: google-github-actions/setup-gcloud@latest
        with:
          version: '372.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      # - name: Set the project ID
      #   run: gcloud config set project single-cistern-420705
      
      # - name: Authenticate with the GKE cluster
      #   run: gcloud container clusters get-credentials your-cluster-name --zone your-cluster-zone
      
      # - name: Apply Kubernetes deployment
      #   run: kubectl apply -f path/to/your/deployment.yaml
