name: Deploy to GKE

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Authenticate with Google Cloud using the service account key file
      - name: Authenticate with Google Cloud using service account key
        run: |
          gcloud auth activate-service-account --key-file=./gcp-auth-key.json
          gcloud config set project single-cistern-420705
          gcloud container clusters get-credentials lpg-mis --region africa-south1

      # Reset kubectl configuration
      - name: Reset kubectl configuration
        run: |
          kubectl config unset users.$(kubectl config view -o=jsonpath='{.users[?(@.name == "gke_gcp_project_name_africa-south1_lpg-mis")].name}')
          kubectl config unset contexts.$(kubectl config current-context)
          kubectl config unset clusters.$(kubectl config view -o=jsonpath='{.clusters[?(@.name == "gke_gcp_project_name_africa-south1_lpg-mis")].name}')

      # Set the kubectl context
      - name: Set kubectl context
        run: |
          gcloud container clusters get-credentials lpg-mis --region africa-south1

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # Build Docker image
      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --tag lpi-mis-api:0.1 \
            .

      # Use gcloud CLI
      - name: Use gcloud CLI
        run: gcloud info

      # Configure kubectl
      - name: Configure kubectl
        run: |
          kubectl config current-context

      # Create NGINX Deployment
      - name: Create NGINX Deployment
        run: |
          kubectl create deployment nginx-deployment --image=nginx:latest
