name: Deploy to GKE

on:
  push:
    branches:
      - develop

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --tag lpi-mis-api:0.1 \
            .

      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: single-cistern-420705
          service_account_key: ./gcp-auth-key.json

      - name: Use gcloud CLI
        run: gcloud info

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials lpg-mis --region africa-south1 --project single-cistern-420705
          
      - name: Get nodes
        run: kubectl get nodes


      
      # - name: Apply Kubernetes deployment
      #   run: |
      #     kubectl apply -f - <<EOF
      #     apiVersion: apps/v1
      #     kind: Deployment
      #     metadata:
      #       name: lpi-mis-api
      #       namespace: test
      #       labels:
      #         app: lpi-mis-api
      #     spec:
      #       replicas: 3
      #       selector:
      #         matchLabels:
      #           app: lpi-mis-api
      #       template:
      #         metadata:
      #           labels:
      #             app: lpi-mis-api
      #         spec:
      #           containers:
      #           - name: lpi-mis-api
      #             image: lpi-mis-api:0.1
      #             ports:
      #             - containerPort: 9998
      #     EOF
