name: Deploy to GKE

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --tag lpi-mis-api:0.1 \
            .
      
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials: ${{ secrets.GCP_AUTH_TOKEN }}

      - name: Set the project ID
        run: gcloud config set project single-cistern-420705
      
      - name: Authenticate with the GKE cluster
        run: gcloud container clusters get-credentials lpg-mis --region africa-south1 --project single-cistern-420705
      
      # - name: Apply Kubernetes deployment
      #   run: |
      #     kubectl apply -f - <<EOF
      #     apiVersion: apps/v1
      #     kind: Deployment
      #     metadata:
      #       name: lpi-mis-api
      #       labels:
      #         app: lpi-mis-api
      #     spec:
      #       replicas: 3
      #       selector:
      #         matchLabels:
      #           app: lpi-mis-api
      #       template:
      #         metadata:
      #           labels:
      #             app: lpi-mis-api
      #         spec:
      #           containers:
      #           - name: lpi-mis-api
      #             image: lpi-mis-api:0.1
      #             ports:
      #             - containerPort: 8080
      #     EOF
