name: Deploy to GKE

on:
  push:
    branches:
      - develop

jobs:
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Authenticate with Google Cloud using the service account key file
      - name: Authenticate with Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=./gcp-auth-key.json
          gcloud config set project single-cistern-420705

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --tag lpi-mis-api:0.1 \
            .


      - name: Use gcloud CLI
        run: gcloud info

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials lpg-mis --region africa-south1 --project single-cistern-420705
          
      # - name: Create NGINX Deployment
      #   run: |
      #     kubectl create deployment nginx-deployment1 --image=nginx:latest





















      
      # - name: Apply Kubernetes deployment
      #   run: |
      #     kubectl apply -f - <<EOF
      #     apiVersion: apps/v1
      #     kind: Deployment
      #     metadata:
      #       name: lpi-mis-api
      #       namespace: test
      #       labels:
      #         app: lpi-mis-api
      #     spec:
      #       replicas: 3
      #       selector:
      #         matchLabels:
      #           app: lpi-mis-api
      #       template:
      #         metadata:
      #           labels:
      #             app: lpi-mis-api
      #         spec:
      #           containers:
      #           - name: lpi-mis-api
      #             image: lpi-mis-api:0.1
      #             ports:
      #             - containerPort: 9998
      #     EOF
