name: deploy-action
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: tiqurabeba
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: tiqurabeba/lpg-mis-api:v0.1

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: single-cistern-420705
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker
          
      - name: Authenticate with Google Cloud
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > /tmp/gcp_sa_key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp_sa_key.json

      - name: Deploy to GKE
        run: |
          # Replace the following commands with your deployment commands
          gcloud container clusters get-credentials lpg-mis --zone africa-south1 --project single-cistern-420705
          kubectl apply -f develop-deployment.yaml
