name: Deploy to GKE

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Authenticate with Google Cloud using the service account key file
      - name: Authenticate with Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=./gcp-auth-key.json
          gcloud config set project single-cistern-420705

      # Install gke-gcloud-auth-plugin using apt-get
      - name: Install gke-gcloud-auth-plugin
        run: sudo apt-get update && sudo apt-get install -y google-cloud-cli-gke-gcloud-auth-plugin

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      # Build Docker image
      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --tag lpi-mis-api:0.1 \
            .

      # Use gcloud CLI
      - name: Use gcloud CLI
        run: gcloud info

      # Configure kubectl
      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials lpg-mis --region africa-south1

      # Create NGINX Deployment
      - name: Create NGINX Deployment
        run: |
          kubectl create deployment nginx-deployment --image=nginx:latest
