name: develop-action

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create deployment YAML
        run: |
          echo '
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: lpg-mis-api-deployment-develop
            namespace: test-environment
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: lpg-mis-api
                env: test
            template:
              metadata:
                labels:
                  app: lpg-mis-api
                  env: test
              spec:
                containers:
                - name: lpg-mis-api
                  image: tiqurabeba/lpg-mis-api:v0.1
                  ports:
                  - containerPort: 9998
                  volumeMounts:
                  - name: data
                    mountPath: /data  # Mount path in the container
                volumes:
                - name: data
                  persistentVolumeClaim:
                    claimName: lpg-mis-api-pvc-develop
          ' > deployment.yaml

      - name: Use Kubernetes cluster credentials
        run: |
          echo "$KUBE_CONFIG" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml

      - name: Apply deployment
        run: |
          kubectl apply -f deployment.yaml
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
