name: develop-action

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_TAG: tiqurabeba/lpg-mis-api:v0.1  # Define the Docker image tag as an environment variable
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: tiqurabeba
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        # with:
        #   username: ${{ secrets.DOCKERHUB_USERNAME }}
        #   password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: tiqurabeba/lpg-mis-api:v0.1
