name: Create Image Develop

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t lpg-mis-api .
          docker save -o lpg-mis-api.tar lpg-mis-api

      - name: Upload Docker image tarball
        uses: actions/upload-artifact@v2
        with:
          name: docker-image
          path: lpg-mis-api.tar
